const darkThemeVariables = {
  '--ant-primary-color': '#177ddc',
  '--ant-primary-color-hover': '#3c9be8',
  '--ant-primary-color-active': '#095cb5',
  '--ant-primary-color-outline': 'rgba(23, 125, 220, 0.2)',
  '--ant-primary-1': '#e6f7ff',
  '--ant-primary-2': '#bde8ff',
  '--ant-primary-3': '#94d6ff',
  '--ant-primary-4': '#67baf5',
  '--ant-primary-5': '#3c9be8',
  '--ant-primary-6': '#177ddc',
  '--ant-primary-7': '#095cb5',
  '--ant-primary-color-deprecated-pure': '',
  '--ant-primary-color-deprecated-l-35': '#afd4f6',
  '--ant-primary-color-deprecated-l-20': '#6aafef',
  '--ant-primary-color-deprecated-t-20': '#4697e3',
  '--ant-primary-color-deprecated-t-50': '#8bbeed',
  '--ant-primary-color-deprecated-f-12': 'rgba(23, 125, 220, 0.12)',
  '--ant-primary-color-active-deprecated-f-30': 'rgba(230, 247, 255, 0.3)',
  '--ant-primary-color-active-deprecated-d-02': '#dcf4ff',
  '--ant-success-color': '#49aa19',
  '--ant-success-color-hover': '#67b839',
  '--ant-success-color-active': '#31850d',
  '--ant-success-color-outline': 'rgba(73, 170, 25, 0.2)',
  '--ant-success-color-deprecated-bg': '#e4ebdd',
  '--ant-success-color-deprecated-border': '#a5d184',
  '--ant-error-color': '#a61d24',
  '--ant-error-color-hover': '#b33b3d',
  '--ant-error-color-active': '#800f19',
  '--ant-error-color-outline': 'rgba(166, 29, 36, 0.2)',
  '--ant-error-color-deprecated-bg': '#e6d9d8',
  '--ant-error-color-deprecated-border': '#cc8885',
  '--ant-warning-color': '#d89614',
  '--ant-warning-color-hover': '#e6b239',
  '--ant-warning-color-active': '#b37407',
  '--ant-warning-color-outline': 'rgba(216, 150, 20, 0.2)',
  '--ant-warning-color-deprecated-bg': '#fffbe6',
  '--ant-warning-color-deprecated-border': '#ffe591',
  '--ant-info-color': '#177ddc',
  '--ant-info-color-deprecated-bg': '#e6f7ff',
  '--ant-info-color-deprecated-border': '#94d6ff',
}

export default darkThemeVariables;
